

services:
  api:
    build: .
    image: api-farmlogistic
    container_name: containerapifarmlogistic
    ports:
      - "8000:8000" 
    environment:
      - DATABASE_URL=postgresql://logisticdb_owner:voCNtruOK43P@ep-crimson-snow-a5my0lyn-pooler.us-east-2.aws.neon.tech/logisticdb?sslmode=require
    restart: unless-stopped

